import type { State } from './types';

export const TID = {
  actionsCard: 'actions-card',
  addAction: 'add-action',
  addArchArrow: 'add-arch-arrow',
  addArchEdgeButton: 'add-arch-edge-button',
  addArchEdgeFrom: 'add-arch-edge-from',
  addArchEdgePlace: 'add-arch-edge-place',
  addArchEdgeTo: 'add-arch-edge-to',
  addArchGroupButton: 'add-arch-group-button',
  addArchGroupIcon: 'add-arch-group-icon',
  addArchGroupName: 'add-arch-group-name',
  addArchGroupParent: 'add-arch-group-parent',
  addArchServiceButton: 'add-arch-service-button',
  addArchServiceFrom: 'add-arch-service-from',
  addArchServiceGroup: 'add-arch-service-group',
  addArchServiceIcon: 'add-arch-service-icon',
  addArchServiceName: 'add-arch-service-name',
  addArchServiceOtherIcon: 'add-arch-service-other-icon',
  addArchServicePlace: 'add-arch-service-place',
  addCard: 'add-card',
  addEdgeButton: 'add-edge-button',
  addEdgeFrom: 'add-edge-from',
  addEdgeLabel: 'add-edge-label',
  addEdgeTo: 'add-edge-to',
  addLaneButton: 'add-lane-button',
  addLaneName: 'add-lane-name',
  addMessage: 'add-message',
  addNodeButton: 'add-node-button',
  addNodeFrom: 'add-node-from',
  addNodeLane: 'add-node-lane',
  addNodeName: 'add-node-name',
  addNodeShape: 'add-node-shape',
  aiClearButton: 'ai-clear-button',
  aiCollected: 'ai-collected',
  aiCopyButton: 'ai-copy-button',
  aiHelpText: 'ai-help-text',
  aiMessage: 'ai-message',
  aiPrompt: 'ai-prompt',
  aiRepairButton: 'ai-repair-button',
  colorsCard: 'colors-card',
  colorsEdge: 'colors-edge',
  colorsEdgeSelect: 'colors-edge-select',
  colorsEdgesClear: 'colors-edges-clear',
  colorsGroup: 'colors-group',
  colorsGroupsAuto: 'colors-groups-auto',
  colorsGroupsClear: 'colors-groups-clear',
  colorsLine: 'colors-line',
  colorsLineCustom: 'colors-line-custom',
  colorsLineDefault: 'colors-line-default',
  colorsNode: 'colors-node',
  colorsNodeSelect: 'colors-node-select',
  colorsNodesAuto: 'colors-nodes-auto',
  colorsNodesClear: 'colors-nodes-clear',
  colorsText: 'colors-text',
  colorsTextBold: 'colors-text-bold',
  colorsTextColor: 'colors-text-color',
  colorsTextReset: 'colors-text-reset',
  colorsTextSize: 'colors-text-size',
  colorsTheme: 'colors-theme',
  copyMarkdown: 'copy-markdown',
  diagramDocumentationButton: 'diagram-documentation-button',
  downloadHTML: 'download-HTML',
  downloadPNG: 'download-PNG',
  downloadSVG: 'download-SVG',
  editCard: 'edit-card',
  editDeleteButton: 'edit-delete-button',
  editDeleteKeepButton: 'edit-delete-keep-button',
  editEdgeDelete: 'edit-edge-delete',
  editEdgeHead: 'edit-edge-head',
  editEdgeLabel: 'edit-edge-label',
  editEdgeLabelButton: 'edit-edge-label-button',
  editEdgeReverse: 'edit-edge-reverse',
  editEdgeSelect: 'edit-edge-select',
  editEdgeStyle: 'edit-edge-style',
  editIconClear: 'edit-icon-clear',
  editIconCurrent: 'edit-icon-current',
  editIconResult: 'edit-icon-result',
  editIconSearch: 'edit-icon-search',
  editMessage: 'edit-message',
  editMoveButton: 'edit-move-button',
  editMoveSelect: 'edit-move-select',
  editObjectSelect: 'edit-object-select',
  editRenameButton: 'edit-rename-button',
  editRenameInput: 'edit-rename-input',
  editShapeSelect: 'edit-shape-select',
  editorFocusToggle: 'editor-focus-toggle',
  editorPaneToggle: 'editor-pane-toggle',
  editorRail: 'editor-rail',
  editorRailExpand: 'editor-rail-expand',
  embedEditLink: 'embed-edit-link',
  embedErrorCard: 'embed-error-card',
  embedFooter: 'embed-footer',
  embedModeToggle: 'embed-mode-toggle',
  embedPreview: 'embed-preview',
  embedRenderError: 'embed-render-error',
  embedSaveLink: 'embed-save-link',
  embedSnippet: 'embed-snippet',
  embedToolbar: 'embed-toolbar',
  errorContainer: 'error-container',
  exportGitLab: 'export-gitlab',
  exportMessage: 'export-message',
  helpButton: 'help-button',
  helpContent: 'help-content',
  helpDialog: 'help-dialog',
  helpSection: 'help-section',
  historyCard: 'history-card',
  historyRevisionsTab: 'history-revisions-tab',
  iconPackFiles: 'icon-pack-files',
  iconPackImport: 'icon-pack-import',
  iconPackList: 'icon-pack-list',
  iconPackPrefix: 'icon-pack-prefix',
  iconPacksCard: 'icon-packs-card',
  iconPickerCollect: 'icon-picker-collect',
  iconPickerEnlarge: 'icon-picker-enlarge',
  iconPickerLargePack: 'icon-picker-large-pack',
  iconPickerLargeResults: 'icon-picker-large-results',
  iconPickerLargeSearch: 'icon-picker-large-search',
  iconPickerMessage: 'icon-picker-message',
  iconPickerPack: 'icon-picker-pack',
  iconPickerResults: 'icon-picker-results',
  iconPickerSearch: 'icon-picker-search',
  layoutCard: 'layout-card',
  layoutDirectionLR: 'layout-direction-lr',
  layoutDirectionTB: 'layout-direction-tb',
  layoutEngineDagre: 'layout-engine-dagre',
  layoutEngineElk: 'layout-engine-elk',
  layoutFit: 'layout-fit',
  layoutMessage: 'layout-message',
  layoutSpacing: 'layout-spacing',
  layoutTitleInput: 'layout-title-input',
  layoutTitleRemove: 'layout-title-remove',
  layoutTitleSet: 'layout-title-set',
  localeToggleButton: 'locale-toggle-button',
  newDiagramCreate: 'new-diagram-create',
  newDiagramDirection: 'new-diagram-direction',
  newDiagramKind: 'new-diagram-kind',
  newDiagramMessage: 'new-diagram-message',
  newDiagramTitle: 'new-diagram-title',
  newDiagramToggle: 'new-diagram-toggle',
  redoButton: 'redo-button',
  resetConfigButton: 'reset-config-button',
  sampleDiagramsCard: 'sample-diagrams-card',
  themeToggleButton: 'theme-toggle-button',
  undoButton: 'undo-button',
  unknownIconChoice: 'unknown-icon-choice',
  unknownIconReplace: 'unknown-icon-replace',
  unknownIcons: 'unknown-icons'
} as const;

export const C = {
  aiLiveEditor: 'ai_live_editor',
  editorChooserDismissedKey: 'mermaid-editor-chooser-dismissed',
  utmSource: 'mermaid_live_editor'
} as const;

export const MERMAID_THEMES = [
  'default',
  'neutral',
  'forest',
  'dark',
  'neo',
  'neo-dark',
  'redux',
  'redux-dark',
  'redux-color',
  'redux-dark-color'
] as const;

export const MERMAID_LOOKS = ['classic', 'handDrawn', 'neo'] as const;

export const defaultState: State = {
  code: `flowchart TD
    A[Christmas] -->|Get money| B(Go shopping)
    B --> C{Let me think}
    C -->|One| D[Laptop]
    C -->|Two| E[iPhone]
    C -->|Three| F[fa:fa-car Car]
  `,
  grid: true,
  // Empty on purpose: mermaid picks its own theme, look and layout per diagram type.
  mermaid: '{}',
  panZoom: true,
  rough: false,
  updateDiagram: true
};
