import type { Locale } from '$/i18n';

/**
 * Local: the Icons card's "Browse" mode (IconBrowser.svelte). A hand-picked set of
 * groups, so someone who does not know an icon's name can look through the usual
 * parts of a system and click one. Each entry is a `prefix:name` from a bundled pack
 * (mermaid's built-in icons as `mermaid:name`) with a short Japanese and English label.
 * iconCategories.test.ts checks every id against the packs. Entries from a logo set,
 * or brand icons, drop out in a MERMAID_BUNDLE_LOGOS=false build: the browser skips
 * icons its packs do not have, and hides a group left empty.
 */

/** One icon: its id, then its Japanese and English labels. */
export type CategoryIcon = readonly [id: string, ja: string, en: string];

export interface IconCategory {
  id: string;
  ja: string;
  en: string;
  icons: readonly CategoryIcon[];
}

export const iconCategories: readonly IconCategory[] = [
  {
    en: 'Standard icons (mermaid)',
    icons: [
      ['mermaid:server', 'サーバー', 'server'],
      ['mermaid:database', 'データベース', 'database'],
      ['mermaid:disk', 'ディスク', 'disk'],
      ['mermaid:internet', 'インターネット', 'internet'],
      ['mermaid:cloud', 'クラウド', 'cloud']
    ],
    id: 'standard',
    ja: '標準アイコン（mermaid）'
  },
  {
    en: 'Servers & storage',
    icons: [
      ['tabler:server', 'サーバー', 'server'],
      ['tabler:server-2', 'サーバー（2台）', 'servers'],
      ['clarity:rack-server-line', 'ラックサーバー', 'rack server'],
      ['clarity:server-line', 'サーバー', 'server'],
      ['clarity:host-line', 'ホスト', 'host'],
      ['clarity:host-group-line', 'ホスト群', 'host group'],
      ['clarity:vm-line', '仮想マシン', 'virtual machine'],
      ['clarity:cluster-line', 'クラスター', 'cluster'],
      ['clarity:resource-pool-line', 'リソースプール', 'resource pool'],
      ['clarity:storage-line', 'ストレージ', 'storage'],
      ['clarity:hard-disk-line', 'ハードディスク', 'hard disk'],
      ['clarity:ssd-line', 'SSD', 'SSD'],
      ['clarity:tape-drive-line', 'テープ装置', 'tape drive'],
      ['clarity:media-changer-line', 'テープライブラリ', 'tape library'],
      ['clarity:backup-line', 'バックアップ', 'backup'],
      ['tabler:server-bolt', 'サーバー（電源）', 'server power'],
      ['tabler:file-database', 'ファイルDB', 'file database'],
      ['carbon:virtual-machine', '仮想マシン', 'virtual machine'],
      ['carbon:bare-metal-server', 'ベアメタル', 'bare metal'],
      ['carbon:server-proxy', 'プロキシサーバー', 'proxy server'],
      ['carbon:data-backup', 'データバックアップ', 'data backup'],
      ['carbon:object-storage', 'オブジェクトストレージ', 'object storage'],
      ['carbon:block-storage', 'ブロックストレージ', 'block storage'],
      ['mdi:nas', 'NAS', 'NAS'],
      ['mdi:server-network', 'ネットワークサーバー', 'network server'],
      ['lucide:hard-drive', 'ドライブ', 'drive'],
      ['lucide:archive', 'アーカイブ', 'archive'],
      ['flat-color-icons:data-backup', 'バックアップ（カラー）', 'backup (colour)'],
      ['flat-color-icons:database', 'ストレージ（カラー）', 'storage (colour)'],
      ['eos-icons:persistent-volume', '永続ボリューム', 'persistent volume'],
      ['eos-icons:network-file-system', 'NFS', 'network file system']
    ],
    id: 'servers',
    ja: 'サーバー・ストレージ'
  },
  {
    en: 'Network equipment',
    icons: [
      ['tabler:router', 'ルーター', 'router'],
      ['clarity:router-line', 'ルーター', 'router'],
      ['tabler:switch', 'スイッチ', 'switch'],
      ['clarity:network-switch-line', 'ネットワークスイッチ', 'network switch'],
      ['carbon:switch-layer-2', 'L2 スイッチ', 'layer-2 switch'],
      ['carbon:switch-layer-3', 'L3 スイッチ', 'layer-3 switch'],
      ['tabler:load-balancer', 'ロードバランサー', 'load balancer'],
      ['carbon:load-balancer-network', 'ネットワーク LB', 'network load balancer'],
      ['carbon:load-balancer-application', 'アプリケーション LB', 'application load balancer'],
      ['clarity:firewall-line', 'ファイアウォール', 'firewall'],
      ['carbon:vpn', 'VPN', 'VPN'],
      ['carbon:gateway', 'ゲートウェイ', 'gateway'],
      ['carbon:gateway-vpn', 'VPN ゲートウェイ', 'VPN gateway'],
      ['carbon:dns-services', 'DNS', 'DNS'],
      ['eos-icons:dns', 'DNS', 'DNS'],
      ['eos-icons:proxy', 'プロキシ', 'proxy'],
      ['eos-icons:ip', 'IP アドレス', 'IP address'],
      ['carbon:vlan', 'VLAN', 'VLAN'],
      ['carbon:network-3', 'ネットワーク', 'network'],
      ['clarity:network-globe-line', 'WAN', 'WAN'],
      ['clarity:cloud-network-line', 'クラウド網', 'cloud network'],
      ['tabler:wifi', 'Wi-Fi', 'Wi-Fi'],
      ['mdi:access-point', 'アクセスポイント', 'access point'],
      ['mdi:router-wireless', '無線ルーター', 'wireless router'],
      ['mdi:ethernet', 'イーサネット', 'Ethernet'],
      ['mdi:lan', 'LAN', 'LAN'],
      ['mdi:server-network-outline', 'ネットワーク機器', 'network device'],
      ['tabler:antenna', 'アンテナ', 'antenna'],
      ['tabler:world', 'インターネット', 'internet'],
      ['lucide:cable', 'ケーブル', 'cable'],
      ['lucide:network', 'ネットワーク構成', 'network'],
      ['eos-icons:ingress', 'イングレス', 'ingress'],
      ['eos-icons:network-policy', 'ネットワークポリシー', 'network policy']
    ],
    id: 'network',
    ja: 'ネットワーク機器'
  },
  {
    en: 'Security',
    icons: [
      ['tabler:firewall-check', 'ファイアウォール', 'firewall'],
      ['carbon:firewall', 'ファイアウォール', 'firewall'],
      ['lucide:brick-wall-fire', '防火壁', 'firewall wall'],
      ['tabler:shield', '盾', 'shield'],
      ['tabler:shield-check', '保護済み', 'protected'],
      ['tabler:shield-lock', 'セキュリティ', 'security'],
      ['clarity:shield-check-line', '検証済み', 'verified'],
      ['tabler:lock', 'ロック', 'lock'],
      ['tabler:key', '鍵', 'key'],
      ['tabler:certificate', '証明書', 'certificate'],
      ['tabler:fingerprint', '生体認証', 'biometrics'],
      ['tabler:password', 'パスワード', 'password'],
      ['tabler:user-shield', '管理者', 'administrator'],
      ['tabler:eye', '監視', 'monitoring'],
      ['tabler:bug', '脆弱性', 'vulnerability'],
      ['carbon:security', 'セキュリティ', 'security'],
      ['carbon:identification', 'ID', 'identity'],
      ['carbon:two-factor-authentication', '二要素認証', 'two-factor auth'],
      ['carbon:password', 'パスワード', 'password'],
      ['eos-icons:secret', 'シークレット', 'secret'],
      ['eos-icons:secure-data', '保護データ', 'secure data'],
      ['eos-icons:pod-security', 'Pod セキュリティ', 'pod security'],
      ['fluent-color:shield-checkmark-48', '保護（カラー）', 'protected (colour)'],
      ['fluent-color:lock-shield-48', 'ロック（カラー）', 'lock (colour)'],
      ['fluent-color:person-key-32', '認証（カラー）', 'sign-in (colour)'],
      ['fluent-color:globe-shield-48', 'Web 保護（カラー）', 'web protection (colour)'],
      ['fluent-color:vault-24', '金庫（カラー）', 'vault (colour)'],
      ['flat-color-icons:lock', 'ロック（カラー）', 'lock (colour)'],
      ['mdi:security-network', 'ネットワーク防御', 'network security'],
      ['mdi:incognito', '匿名化', 'anonymous']
    ],
    id: 'security',
    ja: 'セキュリティ'
  },
  {
    en: 'Cloud & SaaS',
    icons: [
      ['tabler:cloud', 'クラウド', 'cloud'],
      ['tabler:cloud-computing', 'クラウド計算', 'cloud computing'],
      ['tabler:cloud-upload', 'アップロード', 'upload'],
      ['tabler:cloud-download', 'ダウンロード', 'download'],
      ['tabler:cloud-lock', 'プライベートクラウド', 'private cloud'],
      ['tabler:api', 'API', 'API'],
      ['tabler:webhook', 'Webhook', 'webhook'],
      ['tabler:world-www', 'Web サイト', 'website'],
      ['clarity:cloud-scale-line', 'スケール', 'scale'],
      ['clarity:cloud-traffic-line', 'トラフィック', 'traffic'],
      ['carbon:cloud-services', 'クラウドサービス', 'cloud services'],
      ['carbon:cloud-satellite', 'エッジ', 'edge'],
      ['carbon:application-web', 'Web アプリ', 'web app'],
      ['carbon:function', '関数（サーバーレス）', 'function'],
      ['carbon:content-delivery-network', 'CDN', 'CDN'],
      ['carbon:queued', 'キュー', 'queue'],
      ['eos-icons:cloud-computing', 'クラウド', 'cloud computing'],
      ['eos-icons:edge-computing', 'エッジ計算', 'edge computing'],
      ['eos-icons:api', 'API', 'API'],
      ['fluent-color:cloud-48', 'クラウド（カラー）', 'cloud (colour)'],
      ['flat-color-icons:synchronize', '同期（カラー）', 'sync (colour)'],
      ['logos:salesforce', 'Salesforce', 'Salesforce'],
      ['logos:slack-icon', 'Slack', 'Slack'],
      ['logos:zoom-icon', 'Zoom', 'Zoom'],
      ['logos:google-workspace', 'Google Workspace', 'Google Workspace'],
      ['logos:box', 'Box', 'Box'],
      ['logos:dropbox', 'Dropbox', 'Dropbox'],
      ['logos:cloudflare-icon', 'Cloudflare', 'Cloudflare'],
      ['logos:atlassian', 'Atlassian', 'Atlassian'],
      ['logos:jira', 'Jira', 'Jira']
    ],
    id: 'cloud',
    ja: 'クラウド・SaaS'
  },
  {
    en: 'Microsoft 365',
    icons: [
      ['logos:microsoft-teams', 'Teams', 'Teams'],
      ['simple-icons:microsoftteams', 'Teams（単色）', 'Teams (mono)'],
      ['simple-icons:microsoftsharepoint', 'SharePoint', 'SharePoint'],
      ['logos:microsoft-onedrive', 'OneDrive', 'OneDrive'],
      ['simple-icons:microsoftoutlook', 'Outlook', 'Outlook'],
      ['simple-icons:microsoftexchange', 'Exchange', 'Exchange'],
      ['simple-icons:microsoftexcel', 'Excel', 'Excel'],
      ['simple-icons:microsoftword', 'Word', 'Word'],
      ['simple-icons:microsoftpowerpoint', 'PowerPoint', 'PowerPoint'],
      ['simple-icons:microsoftonenote', 'OneNote', 'OneNote'],
      ['simple-icons:microsoftaccess', 'Access', 'Access'],
      ['simple-icons:microsoftvisio', 'Visio', 'Visio'],
      ['simple-icons:microsoftoffice', 'Microsoft 365', 'Microsoft 365'],
      ['simple-icons:powerapps', 'Power Apps', 'Power Apps'],
      ['simple-icons:powerautomate', 'Power Automate', 'Power Automate'],
      ['logos:microsoft-power-bi', 'Power BI', 'Power BI'],
      ['simple-icons:powerpages', 'Power Pages', 'Power Pages'],
      ['simple-icons:dynamics365', 'Dynamics 365', 'Dynamics 365'],
      ['mdi:microsoft-sharepoint', 'SharePoint（MDI）', 'SharePoint (MDI)'],
      ['mdi:microsoft-yammer', 'Viva Engage', 'Viva Engage'],
      ['logos:microsoft-windows-icon', 'Windows', 'Windows'],
      ['logos:microsoft-edge', 'Edge', 'Edge'],
      ['fluent-color:people-team-48', 'チーム', 'team'],
      ['fluent-color:chat-multiple-24', 'チャット', 'chat'],
      ['fluent-color:mail-48', 'メール', 'mail'],
      ['fluent-color:calendar-48', '予定表', 'calendar'],
      ['fluent-color:document-48', 'ドキュメント', 'document'],
      ['fluent-color:document-folder-24', 'ドキュメントライブラリ', 'document library'],
      ['fluent-color:approvals-app-32', '承認', 'approvals'],
      ['fluent-color:shifts-32', 'シフト', 'shifts'],
      ['fluent-color:org-48', '組織', 'organisation'],
      ['fluent-color:video-48', '会議', 'meeting'],
      ['fluent-color:bot-sparkle-24', 'Copilot・ボット', 'Copilot / bot'],
      ['fluent-color:person-key-32', 'サインイン（Entra ID）', 'sign-in (Entra ID)'],
      ['fluent-color:phone-laptop-32', '管理デバイス（Intune）', 'managed devices (Intune)'],
      ['fluent-color:apps-48', 'アプリ', 'apps']
    ],
    id: 'm365',
    ja: 'Microsoft 365'
  },
  {
    en: 'AWS / Azure / Google Cloud',
    icons: [
      ['logos:aws', 'AWS', 'AWS'],
      ['logos:aws-ec2', 'EC2', 'EC2'],
      ['logos:aws-lambda', 'Lambda', 'Lambda'],
      ['logos:aws-s3', 'S3', 'S3'],
      ['logos:aws-rds', 'RDS', 'RDS'],
      ['logos:aws-dynamodb', 'DynamoDB', 'DynamoDB'],
      ['logos:aws-vpc', 'VPC', 'VPC'],
      ['logos:aws-elb', 'ELB', 'ELB'],
      ['logos:aws-route53', 'Route 53', 'Route 53'],
      ['logos:aws-cloudfront', 'CloudFront', 'CloudFront'],
      ['logos:aws-api-gateway', 'API Gateway', 'API Gateway'],
      ['logos:aws-sqs', 'SQS', 'SQS'],
      ['logos:aws-sns', 'SNS', 'SNS'],
      ['logos:aws-iam', 'IAM', 'IAM'],
      ['logos:aws-waf', 'WAF', 'WAF'],
      ['logos:aws-ecs', 'ECS', 'ECS'],
      ['logos:aws-eks', 'EKS', 'EKS'],
      ['logos:aws-cloudwatch', 'CloudWatch', 'CloudWatch'],
      ['logos:microsoft-azure', 'Azure', 'Azure'],
      ['simple-icons:azurefunctions', 'Azure Functions', 'Azure Functions'],
      ['simple-icons:azuredevops', 'Azure DevOps', 'Azure DevOps'],
      ['devicon:azuresqldatabase', 'Azure SQL Database', 'Azure SQL Database'],
      ['devicon:azuredatafactory', 'Data Factory', 'Data Factory'],
      ['logos:google-cloud', 'Google Cloud', 'Google Cloud'],
      ['logos:google-cloud-run', 'Cloud Run', 'Cloud Run'],
      ['logos:google-cloud-functions', 'Cloud Functions', 'Cloud Functions'],
      ['simple-icons:googlebigquery', 'BigQuery', 'BigQuery'],
      ['simple-icons:googlecloudstorage', 'Cloud Storage', 'Cloud Storage'],
      ['simple-icons:googlepubsub', 'Pub/Sub', 'Pub/Sub'],
      ['logos:firebase', 'Firebase', 'Firebase']
    ],
    id: 'hyperscalers',
    ja: 'AWS / Azure / Google Cloud'
  },
  {
    en: 'Databases',
    icons: [
      ['tabler:database', 'データベース', 'database'],
      ['tabler:database-cog', 'DB 設定', 'database settings'],
      ['tabler:database-export', 'エクスポート', 'export'],
      ['tabler:database-import', 'インポート', 'import'],
      ['lucide:database', 'データベース', 'database'],
      ['lucide:database-backup', 'DB バックアップ', 'database backup'],
      ['lucide:database-zap', 'キャッシュ', 'cache'],
      ['carbon:data-base', 'データベース', 'database'],
      ['carbon:data-structured', 'データウェアハウス', 'data warehouse'],
      ['carbon:data-table', 'テーブル', 'table'],
      ['carbon:datastore', 'データストア', 'datastore'],
      ['clarity:data-cluster-line', 'データクラスター', 'data cluster'],
      ['eos-icons:big-data', 'ビッグデータ', 'big data'],
      ['eos-icons:database-migration', 'DB 移行', 'database migration'],
      ['fluent-color:book-database-32', 'データ（カラー）', 'data (colour)'],
      ['flat-color-icons:database', 'DB（カラー）', 'database (colour)'],
      ['logos:postgresql', 'PostgreSQL', 'PostgreSQL'],
      ['logos:mysql-icon', 'MySQL', 'MySQL'],
      ['devicon:microsoftsqlserver', 'SQL Server', 'SQL Server'],
      ['devicon:oracle', 'Oracle', 'Oracle'],
      ['logos:mongodb-icon', 'MongoDB', 'MongoDB'],
      ['logos:redis', 'Redis', 'Redis'],
      ['logos:elasticsearch', 'Elasticsearch', 'Elasticsearch'],
      ['logos:sqlite', 'SQLite', 'SQLite'],
      ['logos:mariadb-icon', 'MariaDB', 'MariaDB'],
      ['logos:snowflake-icon', 'Snowflake', 'Snowflake']
    ],
    id: 'database',
    ja: 'データベース'
  },
  {
    en: 'Devices',
    icons: [
      ['tabler:device-desktop', 'デスクトップ PC', 'desktop PC'],
      ['tabler:device-laptop', 'ノート PC', 'laptop'],
      ['tabler:device-mobile', 'スマートフォン', 'smartphone'],
      ['tabler:device-tablet', 'タブレット', 'tablet'],
      ['tabler:device-tv', 'ディスプレイ', 'display'],
      ['tabler:printer', 'プリンター', 'printer'],
      ['tabler:scan', 'スキャナー', 'scanner'],
      ['tabler:camera', 'カメラ', 'camera'],
      ['tabler:device-cctv', '監視カメラ', 'CCTV'],
      ['tabler:phone', '電話', 'phone'],
      ['tabler:headset', 'ヘッドセット', 'headset'],
      ['tabler:keyboard', 'キーボード', 'keyboard'],
      ['tabler:usb', 'USB', 'USB'],
      ['tabler:cpu', 'CPU', 'CPU'],
      ['tabler:device-watch', 'ウェアラブル', 'wearable'],
      ['clarity:thin-client-line', 'シンクライアント', 'thin client'],
      ['clarity:computer-line', 'パソコン', 'computer'],
      ['clarity:internet-of-things-line', 'IoT', 'IoT'],
      ['eos-icons:iot', 'IoT', 'IoT'],
      ['carbon:iot-platform', 'IoT プラットフォーム', 'IoT platform'],
      ['mdi:cellphone-link', 'モバイル連携', 'mobile link'],
      ['mdi:barcode-scan', 'バーコード', 'barcode scanner'],
      ['fluent-color:laptop-48', 'ノート PC（カラー）', 'laptop (colour)'],
      ['fluent-color:phone-48', 'スマートフォン（カラー）', 'phone (colour)'],
      ['flat-color-icons:print', 'プリンター（カラー）', 'printer (colour)'],
      ['flat-color-icons:multiple-devices', '複数端末（カラー）', 'devices (colour)']
    ],
    id: 'devices',
    ja: '端末・デバイス'
  },
  {
    en: 'People & organisation',
    icons: [
      ['tabler:user', '利用者', 'user'],
      ['tabler:users', '利用者（複数）', 'users'],
      ['tabler:users-group', 'グループ', 'group'],
      ['tabler:user-circle', 'アカウント', 'account'],
      ['tabler:user-check', '承認者', 'approver'],
      ['tabler:user-cog', '管理者', 'administrator'],
      ['tabler:user-question', '問い合わせ', 'enquirer'],
      ['tabler:headset', 'サポート窓口', 'help desk'],
      ['tabler:building', 'オフィス', 'office'],
      ['tabler:building-skyscraper', '本社', 'headquarters'],
      ['tabler:building-factory-2', '工場', 'factory'],
      ['tabler:building-store', '店舗', 'store'],
      ['tabler:building-warehouse', '倉庫', 'warehouse'],
      ['tabler:home', '自宅・在宅勤務', 'home'],
      ['tabler:hierarchy-2', '組織図', 'hierarchy'],
      ['tabler:affiliate', '取引先', 'partners'],
      ['tabler:truck-delivery', '配送', 'delivery'],
      ['fluent-color:person-48', '人（カラー）', 'person (colour)'],
      ['fluent-color:people-48', '人々（カラー）', 'people (colour)'],
      ['fluent-color:people-community-48', 'コミュニティ（カラー）', 'community (colour)'],
      ['fluent-color:building-people-24', '部署（カラー）', 'department (colour)'],
      ['fluent-color:guest-48', 'ゲスト（カラー）', 'guest (colour)'],
      ['fluent-color:contact-card-48', '名刺（カラー）', 'contact card (colour)'],
      ['flat-color-icons:businessman', 'ビジネスパーソン（カラー）', 'business person (colour)'],
      ['flat-color-icons:businesswoman', 'ビジネスパーソン（カラー）', 'business person (colour)'],
      ['flat-color-icons:customer-support', 'サポート（カラー）', 'support (colour)'],
      ['flat-color-icons:conference-call', '会議（カラー）', 'meeting (colour)'],
      ['flat-color-icons:organization', '組織（カラー）', 'organisation (colour)']
    ],
    id: 'people',
    ja: '人・組織'
  },
  {
    en: 'Documents & business',
    icons: [
      ['tabler:file-text', '文書', 'document'],
      ['tabler:file-spreadsheet', '表計算', 'spreadsheet'],
      ['tabler:file-invoice', '請求書', 'invoice'],
      ['tabler:file-certificate', '契約書', 'contract'],
      ['tabler:files', 'ファイル', 'files'],
      ['tabler:folder', 'フォルダー', 'folder'],
      ['tabler:clipboard-list', 'チェックリスト', 'checklist'],
      ['tabler:clipboard-check', '承認済み', 'approved'],
      ['tabler:mail', 'メール', 'mail'],
      ['tabler:calendar', '予定', 'calendar'],
      ['tabler:clock', '時刻・バッチ', 'clock / batch'],
      ['tabler:report-analytics', 'レポート', 'report'],
      ['tabler:chart-bar', 'グラフ', 'chart'],
      ['tabler:receipt', '領収書', 'receipt'],
      ['tabler:currency-yen', '金額', 'amount'],
      ['tabler:shopping-cart', '注文', 'order'],
      ['tabler:package', '荷物', 'package'],
      ['tabler:rubber-stamp', '押印', 'stamp'],
      ['tabler:writing-sign', '署名', 'signature'],
      ['tabler:message', 'メッセージ', 'message'],
      ['fluent-color:document-text-48', '文書（カラー）', 'document (colour)'],
      ['fluent-color:clipboard-task-24', 'タスク（カラー）', 'task (colour)'],
      ['fluent-color:calendar-checkmark-24', '予定確定（カラー）', 'confirmed (colour)'],
      ['fluent-color:data-pie-32', '分析（カラー）', 'analytics (colour)'],
      ['fluent-color:receipt-32', '伝票（カラー）', 'receipt (colour)'],
      ['flat-color-icons:document', '文書（カラー）', 'document (colour)'],
      ['flat-color-icons:folder', 'フォルダー（カラー）', 'folder (colour)'],
      ['flat-color-icons:approval', '承認（カラー）', 'approval (colour)'],
      ['flat-color-icons:bar-chart', 'グラフ（カラー）', 'chart (colour)'],
      ['flat-color-icons:planner', '計画（カラー）', 'planner (colour)']
    ],
    id: 'business',
    ja: '書類・業務'
  },
  {
    en: 'Development & operations',
    icons: [
      ['tabler:code', 'コード', 'code'],
      ['tabler:terminal-2', 'ターミナル', 'terminal'],
      ['tabler:git-branch', 'ブランチ', 'branch'],
      ['tabler:git-merge', 'マージ', 'merge'],
      ['tabler:git-pull-request', 'プルリクエスト', 'pull request'],
      ['tabler:bug', 'バグ', 'bug'],
      ['tabler:test-pipe', 'テスト', 'test'],
      ['tabler:rocket', 'リリース', 'release'],
      ['tabler:box', 'コンテナ', 'container'],
      ['tabler:settings', '設定', 'settings'],
      ['tabler:activity', '監視', 'monitoring'],
      ['tabler:bell', '通知', 'alert'],
      ['tabler:list-details', 'ログ・キュー', 'log / queue'],
      ['tabler:robot', 'AI・ロボット', 'AI / robot'],
      ['carbon:continuous-integration', 'CI', 'CI'],
      ['carbon:continuous-deployment', 'CD', 'CD'],
      ['carbon:container-registry', 'コンテナレジストリ', 'container registry'],
      ['clarity:ci-cd-line', 'CI/CD', 'CI/CD'],
      ['clarity:container-line', 'コンテナ', 'container'],
      ['eos-icons:pipeline', 'パイプライン', 'pipeline'],
      ['eos-icons:pod', 'Pod', 'pod'],
      ['eos-icons:namespace', '名前空間', 'namespace'],
      ['eos-icons:cronjob', '定期ジョブ', 'cron job'],
      ['eos-icons:monitoring', 'モニタリング', 'monitoring'],
      ['eos-icons:deploy', 'デプロイ', 'deploy'],
      ['eos-icons:config-map', '設定マップ', 'config map'],
      ['logos:docker-icon', 'Docker', 'Docker'],
      ['logos:kubernetes', 'Kubernetes', 'Kubernetes'],
      ['logos:github-icon', 'GitHub', 'GitHub'],
      ['logos:gitlab', 'GitLab', 'GitLab'],
      ['logos:jenkins', 'Jenkins', 'Jenkins'],
      ['logos:terraform-icon', 'Terraform', 'Terraform'],
      ['logos:ansible', 'Ansible', 'Ansible'],
      ['logos:grafana', 'Grafana', 'Grafana'],
      ['logos:prometheus', 'Prometheus', 'Prometheus']
    ],
    id: 'devops',
    ja: '開発・運用'
  }
];

/** A category's name in the given language. */
export const categoryName = (category: IconCategory, locale: Locale): string =>
  locale === 'ja' ? category.ja : category.en;

/** An entry's short label in the given language. */
export const iconLabel = (icon: CategoryIcon, locale: Locale): string =>
  locale === 'ja' ? icon[1] : icon[2];
